#!/bin/bash
#
# Molly Trading Module - Morning Brief Generator
# Usage: ./scripts/trading-brief.sh
#

VAULT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../vault" && pwd)"
TRADING_DIR="$VAULT_DIR/01-trading"

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              MORNING TRADING BRIEF                           ║${NC}"
echo -e "${BLUE}║              $(date '+%A, %B %d, %Y - %H:%M %Z')${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# 1. Load Current State
echo "📊 CURRENT POSITIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -f "$TRADING_DIR/_state.md" ]; then
    # Extract open positions section
    grep -A 20 "## Open Positions" "$TRADING_DIR/_state.md" | head -15
else
    echo "No state file found. Create one at: $TRADING_DIR/_state.md"
fi
echo ""

# 2. Key Levels
echo "🎯 KEY LEVELS FOR TODAY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -f "$TRADING_DIR/_state.md" ]; then
    grep -A 10 "## Today's Key Levels" "$TRADING_DIR/_state.md" | head -12
fi
echo ""

# 3. Economic Calendar (placeholder - would integrate with API)
echo "📅 ECONOMIC CALENDAR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Today: $(date '+%Y-%m-%d')"
echo ""
echo "⚠️  HIGH IMPACT:"
echo "   • FOMC Minutes - 14:00 EST (NO TRADES 14:00-15:00)"
echo ""
echo "📊 MEDIUM IMPACT:"
echo "   • Initial Jobless Claims - 08:30 EST"
echo ""

# 4. Overnight Market Context
echo "🌙 OVERNIGHT CONTEXT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Fetching pre-market data..."
# Would integrate with Polygon.io or similar
# Placeholder values:
echo "   NAS100: Pre-market +45 pts (+0.22%)"
echo "   SPY: Pre-market +0.8%"
echo "   VIX: 18.5 (elevated, watch for expansion)"
echo ""

# 5. Layer 3 Analysis
echo "🧠 LAYER 3 GAME THEORY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -f "$TRADING_DIR/_state.md" ]; then
    grep -A 5 "## Layer 3 Status" "$TRADING_DIR/_state.md"
fi
echo ""

# 6. Today's Setup Watchlist
echo "👀 SETUPS TO WATCH"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -f "$TRADING_DIR/_state.md" ]; then
    grep -A 10 "## Active Setups" "$TRADING_DIR/_state.md" | head -12
fi
echo ""

# 7. Action Items
echo "✅ ACTION ITEMS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Pre-market (08:30-09:25):"
echo "   ☐ Review overnight gaps"
echo "   ☐ Check economic calendar"
echo "   ☐ Confirm TradeLocker connection"
echo "   ☐ Set price alerts at key levels"
echo ""
echo "Market Open (09:30):"
echo "   ☐ Watch for opening drive fade"
echo "   ☐ Monitor sweep of 20400 liquidity"
echo "   ☐ Wait for Layer 3 confirmation before entry"
echo ""

# 8. Risk Reminders
echo "⚠️  RISK REMINDERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   • NO trades 14:00-15:00 (FOMC)"
echo "   • Max 1% risk per trade"
echo "   • Move to breakeven after 1R"
echo "   • Journal every trade with screenshot"
echo ""

# Save to today's log
TODAY_LOG="$TRADING_DIR/log/$(date '+%Y-%m-%d').md"
if [ ! -f "$TODAY_LOG" ]; then
    cat > "$TODAY_LOG" << EOF
---
date: $(date '+%Y-%m-%d')
domain: trading
type: daily-log
---

# $(date '+%Y-%m-%d') - Trading Log

## Pre-Market Brief ($(date '+%H:%M'))
Generated by Molly Trading Module

### Key Levels
- Support: 20400 (liquidity pool)
- Resistance: 20550 (prior high)
- Invalidation: 20350

### Economic Events
- FOMC Minutes: 14:00 EST (NO TRADE WINDOW)
- Jobless Claims: 08:30 EST

### Overnight Context
- NAS100: +45 pts pre-market
- VIX: 18.5 (elevated)

### Layer 3 Status
$(grep -A 3 "## Layer 3 Status" "$TRADING_DIR/_state.md" 2>/dev/null | tail -3)

## Session Notes

### 09:30 - Market Open
[Fill in as day progresses]

## Post-Session Review
[Fill at market close]
EOF
    echo "✅ Created today's log: $TODAY_LOG"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Brief complete. Trade safe. 🎯"
echo ""